### PR TITLE
BG-11937: Add publish.sh script

### PR DESCRIPTION
**Pull request by tylerlevine**
* Add build script for consistency with other projects
* Call build script from prepublish

### CODE REVIEW

**Comment by tylerlevine** [comment]
maybe @OttoAllmendinger could review, since this script is largely the same as the one added to @bitgo/unspents

**Comment by dannybitgo** [comment]
I'm happy to review, though I'm not quite sure how I can test that this works

**Comment by james8nguyen** [comment]
@tylerlevine , the reason I have paused on reviewing your PR is because I have been working on a similar script. Guess we did not collaborate or communicate.

It is in my dev branch, origin/BRE-439-AutomatePublishProcess. Although not completed yet, here are some key differences.
1) It can also be used for unspents, BitgoD, CLI v1 and v2. Being passed in as a required input parameter.
2) It is based on tag instead of branch. Being passed in as a required input parameter.
3) Can be run locally or via a Jenkins job. A little more complicated here due to usr account and otp but doable.

BTW, we have been publishing @bitgo/unspents using the procedure below. Your added script under the unspents repo has changed the procedure which should be fine except it should be communicated.

`npm publish https://github.com/BitGo/unspents/archive/0.5.1.tar.gz --access public`

**Comment by tylerlevine** [comment]
> @tylerlevine , the reason I have paused on reviewing your PR is because I have been working on a similar script. Guess we did not collaborate or communicate.
> 
> It is in my dev branch, origin/BRE-439-AutomatePublishProcess. Although not completed yet, here are some key differences.
> 
>     1. It can also be used for unspents, BitgoD, CLI v1 and v2. Being passed in as a required input parameter.
> 
>     2. It is based on tag instead of branch. Being passed in as a required input parameter.
> 
>     3. Can be run locally or via a Jenkins job. A little more complicated here due to usr account and otp but doable.
> 
> 
> BTW, we have been publishing @bitgo/unspents using the procedure below. Your added script under the unspents repo has changed the procedure which should be fine except it should be communicated.
> 
> `npm publish https://github.com/BitGo/unspents/archive/0.5.1.tar.gz --access public`

I'd like releases for bitgojs to be done using only the included publish script from now on (same is true for @bitgo/unspents). Pull requests to the existing script are welcome, but all publish scripts should be committed to the repo.

**Comment by james8nguyen** [comment]
> > @tylerlevine , the reason I have paused on reviewing your PR is because I have been working on a similar script. Guess we did not collaborate or communicate.
> > It is in my dev branch, origin/BRE-439-AutomatePublishProcess. Although not completed yet, here are some key differences.
> > ```
> > 1. It can also be used for unspents, BitgoD, CLI v1 and v2. Being passed in as a required input parameter.
> > 
> > 2. It is based on tag instead of branch. Being passed in as a required input parameter.
> > 
> > 3. Can be run locally or via a Jenkins job. A little more complicated here due to usr account and otp but doable.
> > ```
> > BTW, we have been publishing @bitgo/unspents using the procedure below. Your added script under the unspents repo has changed the procedure which should be fine except it should be communicated.
> > `npm publish https://github.com/BitGo/unspents/archive/0.5.1.tar.gz --access public`
> 
> @james8nguyen I'd like releases for bitgojs to be done using only the included publish script from now on, starting with the next regular sprint release (same is true for @bitgo/unspents). Pull requests to the existing script are welcome, but all publish scripts should be committed to the repo.

Agreed but my points in my earlier comments were obviously different.

Since we publish based on a specific release tag instead of just a branch (not necessary at tip of such branch), I'm going to request for changes. True for BitGoJS and unspents.

**Comment by tylerlevine** [comment]
Updated to make publishing tags (and any ref) more intuitive.

**Pull request merged**
