### PR TITLE
chore(utxo-lib): depend on @bitgo/bitcoinjs-lib@6.0.0

### PR DESCRIPTION
**Pull request by OttoAllmendinger**
Fix nonstandard `Signer` import

Issue: BG-36608

### CODE REVIEW

**Review by sangaman — DISMISSED** [review]
6.0 change looks good but I forgot where we ended up with discussing the `.drone.yml` file. I thought we want to keep it after all?

**Comment by OttoAllmendinger** [comment]
we do, I'm just looking for a good way to generate it and check the correct compilation via CI

**Review by sangaman — DISMISSED** [review]
I get the same output from running `drone jsonnet --format`, weird that it's rewriting the whole file but I guess that's how it goes.

**Comment by tylerlevine** [comment]
I think this broke drone, when it hangs like this usually that means it can't parse the .drone.yml successfully

**Review by tylerlevine — CHANGES_REQUESTED** [review]
please take a look at the drone build not getting triggered - usually this means there's a problem with the .drone.yml file

**Comment by tylerlevine** [comment]
looks like using the provided `yarn gen-drone` script produced a valid .drone.yml with the latest changes.

I'm running 
```
$ drone --version
drone version 1.2.4
```

I wonder if a newer version of drone-cli is producing the different yaml?

**Review by tylerlevine — APPROVED** [review]

**Pull request merged**
