### PR TITLE
feat(statics): added offchain support for ANKR, PENDLE, OM and OCEAN

### PR DESCRIPTION
**Pull request by raj-bitgo**
Ticket: [PX-3902](https://bitgoinc.atlassian.net/browse/PX-3902)

[PX-3902]: https://bitgoinc.atlassian.net/browse/PX-3902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ravneet-bitgo — COMMENTED** [review]
flush

**Review by sachushaji — COMMENTED** [review]
@raj-bitgo , fix your commit message, seems lint errors

**Review by shivagupta94 — DISMISSED** [review]
LGTM

**Review by ravneet-bitgo — CHANGES_REQUESTED** [review]
Please squash the commits

**Review by ravneet-bitgo — APPROVED** [review]

**Review by Phani024 — COMMENTED** [review]
Please squash the commits.

**Review by mandalarnav — DISMISSED** [review]

**Pull request merged**
