### PR TITLE
chore(utxo-lib): update to `@bitgo/bitcoinjs-lib@6.1.0-rc.2`

### PR DESCRIPTION
**Pull request by tylerlevine**
Ticket: BG-39039

### CODE REVIEW

**Review by brandonblack — CHANGES_REQUESTED** [review]
I _think_ we should update this in `account-lib` too to prevent issues in WP later.

**Comment by tylerlevine** [comment]
> I _think_ we should update this in `account-lib` too to prevent issues in WP later.

We only use `ECPair` and `networks` in account-lib, I don't think these have really changed.

**Comment by brandonblack** [comment]
> > I _think_ we should update this in `account-lib` too to prevent issues in WP later.
> 
> We only use `ECPair` and `networks` in account-lib, I don't think these have really changed.

The problem is that account-lib's version clobbers the one pulled by utxo-lib when WP pulls both :(. That's what Luis' was working around by putting bitcoinjs-lib directly in WP's package.json

**Review by sangaman — APPROVED** [review]
Changes look good, possible account-lib concern notwithstanding

**Review by brandonblack — APPROVED** [review]

**Pull request merged**
