### PR TITLE
fix: update invalid files for depcheck

### PR DESCRIPTION
**Pull request by mmcshinsky-bitgo**
Update files considered invalid by `depcheck` while honoring language syntax and tests.

BG-50968

### CODE REVIEW

**Review by tylerlevine — CHANGES_REQUESTED** [review]
looks good but please check build

**Comment by mmcshinsky-bitgo** [comment]
> definitely solves the previous problem of false positives, but the way we're logging in CI doesn't look correct: https://github.com/BitGo/BitGoJS/runs/7026769360?check_suite_focus=true
> 
> ```
> Warning: devDependencies declared but not detected in code - express 
>  - cashaddress 
>  - ecurve 
>  - eol 
>  - openpgp 
>  - sanitize-html 
>  - karma-mocha 
>  - minimist 
>  - process 
>  - q 
>  - request 
>  - request-promise 
>  - sjcl 
>  - supertest 
>  - terser 
>  - wat2wasm 
>  - bluebird 
>  - bignumber.js 
>  - mocha-junit-reporter 
>  - mocha-lcov-reporter 
>  - supertest 
>  - supertest-as-promised 
>  - babel-loader 
>  - process 
>  - bech32 
>  - secp
>  - tweetnacl 
>  - url 
>  - lodash 
>  - lodash 
>  - lodash.combinations 
>  - mocha-junit-reporter 
>  - axios 
>  - debug 
>  - fs-extra 
>  - css-loader 
>  - file-loader 
>  - postcss 
>  - postcss-loader 
>  - postcss-preset-env 
>  - sass 
>  - sass-loader 
>  - style-loader 
>  - ts-loader 
>  Warning: devDependencies declared but not detected in code - sdk-api 
>  Warning: dependencies declared but not detected in code - sdk-coin-avaxp 
>  Warning: devDependencies declared but not detected in code - sdk-coin-cspr 
>  Warning: dependencies declared but not detected in code - sdk-coin-xrp 
>  Warning: dependencies declared but not detected in code - sdk-test 
>  Warning: dependencies declared but not detected in code - unspents 
>  Warning: devDependencies declared but not detected in code - unspents 
>  Warning: devDependencies declared but not detected in code - utxo-lib 
>  Warning: devDependencies declared but not detected in code - web-demo
> ```

I'll look into it. This is something definitely on the github side and not local.

**Comment by mmcshinsky-bitgo** [comment]
@bitgoAaron All fixed. Github ci moved console.warn below console.log for some reason.

**Review by bitgoAaron — DISMISSED** [review]

**Comment by mmcshinsky-bitgo** [comment]
@tylerlevine Can I get a reapproval on this one? Looks like a need both due to the earlier change requests. Thanks!

**Review by bitgoAaron — DISMISSED** [review]

**Review by bitgoAaron — APPROVED** [review]

**Pull request merged**
