### PR TITLE
Stlx 16584 sdk keypair wallet refactor account lib avaxp into avax lib

### PR DESCRIPTION
**Pull request by priyeshag**

### CODE REVIEW

**Review by mmcshinsky-bitgo — CHANGES_REQUESTED** [review]
Add `.DS_Store` to .gitignore.

**Comment by priyeshag** [comment]
> Add `.DS_Store` to .gitignore.

Done

**Comment by mmcshinsky-bitgo** [comment]
@priyeshag Looks like there is a merge conflict and you'll want to rebase from master.

**Comment by mmcshinsky-bitgo** [comment]
@shiksb Who owns this PR?

**Comment by mmcshinsky-bitgo** [comment]
User is deactivated with no internal response. Closing.

**Pull request closed without merging**
