### PR TITLE
chore(root): publish modules

### PR DESCRIPTION
**Pull request by alebusse**
- @bitgo/abstract-cosmos@1.13.0
 - @bitgo/abstract-eth@6.0.0
 - @bitgo/abstract-utxo@3.23.0
 - @bitgo/account-lib@9.0.0
 - bitgo@24.0.0
 - @bitgo/blockapis@1.7.21
 - @bitgo/express@9.47.0
 - @bitgo/key-card@0.8.0
 - @bitgo/sdk-api@1.29.0
 - @bitgo/sdk-coin-ada@2.22.0
 - @bitgo/sdk-coin-algo@1.12.0
 - @bitgo/sdk-coin-arbeth@6.0.0
 - @bitgo/sdk-coin-atom@3.13.0
 - @bitgo/sdk-coin-avaxc@2.14.0
 - @bitgo/sdk-coin-avaxp@3.8.0
 - @bitgo/sdk-coin-bch@1.5.18
 - @bitgo/sdk-coin-bcha@1.7.18
 - @bitgo/sdk-coin-bera@1.7.0
 - @bitgo/sdk-coin-bld@1.11.0
 - @bitgo/sdk-coin-bsc@8.0.0
 - @bitgo/sdk-coin-bsv@1.5.18
 - @bitgo/sdk-coin-btc@1.7.18
 - @bitgo/sdk-coin-btg@1.5.18
 - @bitgo/sdk-coin-celo@1.5.18
 - @bitgo/sdk-coin-coreum@6.0.0
 - @bitgo/sdk-coin-cspr@1.12.0
 - @bitgo/sdk-coin-dash@1.5.18
 - @bitgo/sdk-coin-doge@1.12.18
 - @bitgo/sdk-coin-dot@3.20.0
 - @bitgo/sdk-coin-eos@1.5.18
 - @bitgo/sdk-coin-etc@1.4.18
 - @bitgo/sdk-coin-eth@9.0.0
 - @bitgo/sdk-coin-eth2@1.4.18
 - @bitgo/sdk-coin-ethw@6.0.0
 - @bitgo/sdk-coin-hash@1.11.0
 - @bitgo/sdk-coin-hbar@1.5.18
 - @bitgo/sdk-coin-injective@1.11.0
 - @bitgo/sdk-coin-islm@1.7.0
 - @bitgo/sdk-coin-ltc@2.2.18
 - @bitgo/sdk-coin-near@1.6.18
 - @bitgo/sdk-coin-opeth@3.0.0
 - @bitgo/sdk-coin-osmo@1.13.0
 - @bitgo/sdk-coin-polygon@6.0.0
 - @bitgo/sdk-coin-rbtc@1.5.18
 - @bitgo/sdk-coin-sei@1.11.0
 - @bitgo/sdk-coin-sol@2.25.0
 - @bitgo/sdk-coin-stx@2.3.18
 - @bitgo/sdk-coin-sui@4.10.0
 - @bitgo/sdk-coin-tia@1.11.0
 - @bitgo/sdk-coin-ton@1.7.0
 - @bitgo/sdk-coin-trx@1.23.0
 - @bitgo/sdk-coin-xlm@2.10.0
 - @bitgo/sdk-coin-xrp@1.7.18
 - @bitgo/sdk-coin-xtz@1.6.18
 - @bitgo/sdk-coin-zec@1.5.18
 - @bitgo/sdk-coin-zeta@1.16.0
 - @bitgo/sdk-core@13.0.0
 - @bitgo/sdk-lib-mpc@8.20.0
 - @bitgo/sdk-rpc-wrapper@1.9.0
 - @bitgo/sdk-test@1.2.48
 - @bitgo/sdk-unified-wallet@3.2.18
 - @bitgo/secp256k1@1.2.13
 - @bitgo/statics@34.0.0
 - @bitgo/unspents@0.33.0
 - @bitgo/utxo-bin@2.32.0
 - @bitgo/utxo-lib@9.21.0
 - @bitgo/utxo-ord@1.6.0
 - @bitgo/web-demo@1.14.0

WP-1057

### CODE REVIEW

**Comment by alebusse** [comment]
TODO: Create a ticket to deprecate node 16 or fix this https://github.com/BitGo/BitGoJS/actions/runs/6975325308/job/18982285030?pr=4088

**Comment by alebusse** [comment]
TODO: Create a ticket to deprecate node 16 or fix this https://github.com/BitGo/BitGoJS/actions/runs/6975325308/job/18982285030?pr=4088

**Comment by mukeshsp** [comment]
@alebusse build is failing with an error 

error @polkadot/x-bigint@12.6.1: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"

**Comment by alebusse** [comment]
> @alebusse build is failing with an error 
> 
> error @polkadot/x-bigint@12.6.1: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"

Is not a required step, this step in particular is installing fresh by removing the yarn.lock. i left a comment about it.

**Review by rushilbg — APPROVED** [review]

**Review by zahin-mohammad — APPROVED** [review]

**Review by margueriteblair — APPROVED** [review]

**Pull request merged**
