### PR TITLE
fix(key-card): reduce size of QR codes

### PR DESCRIPTION
**Pull request by LeoKotschenreuther**
Upon printing some key cards it was realized that some QR codes could get too dense for being able to scanned by a phone. This commit reduces the density of the QR codes and arranges them properly across multiple pages if necessary.

Ticket: BG-67970

## Test instructions

1. Check out this branch locally
2. Run `yarn install` in the root of the repository
3. `cd modules/web-demo`
4. `yarn dev`
5. Go to http://localhost:8080/keycard
6. Download all three types of key cards and compare to the ones attached to this PR.

[BitGo Keycard for SMHA Polygon Wallet.pdf](https://github.com/BitGo/BitGoJS/files/10734322/BitGo.Keycard.for.SMHA.Polygon.Wallet.pdf)
[BitGo Keycard for Hot ETH TSS Wallet.pdf](https://github.com/BitGo/BitGoJS/files/10734323/BitGo.Keycard.for.Hot.ETH.TSS.Wallet.pdf)
[BitGo Keycard for Hot LTC Wallet.pdf](https://github.com/BitGo/BitGoJS/files/10734324/BitGo.Keycard.for.Hot.LTC.Wallet.pdf)

### CODE REVIEW

**Review by pranavjain97 — COMMENTED** [review]
Could you attach a sample PDF after this code change on the PR? Maybe a before and after would be helpful to understand the difference.

**Comment by LeoKotschenreuther** [comment]
> Could you attach a sample PDF after this code change on the PR? Maybe a before and after would be helpful to understand the difference.

Sorry about that, I recreated the PR and forgot to copy the sample PDFs over. Fixed.

**Review by pranavjain97 — DISMISSED** [review]
Lgtm. As discussed, you will be making the font fix and combining the key shares section in a follow-up?

**Comment by LeoKotschenreuther** [comment]
Font fixed and new PDFs uploaded

**Review by pranavjain97 — APPROVED** [review]

**Review by sachushaji — APPROVED** [review]

**Pull request merged**
