### PR TITLE
fix(account-lib): update dot feeOption jsdoc

### PR DESCRIPTION
**Pull request by byhow**
Ticket: STLX-8335

### CODE REVIEW

**Review by lcovar — DISMISSED** [review]
lgtm

**Review by tylerlevine — CHANGES_REQUESTED** [review]
please correct typo in commit message

**Comment by byhow** [comment]
commit message typo corrected

**Review by 0xabrarhussain — APPROVED** [review]

**Comment by byhow** [comment]
Hi @tylerlevine, do you mind ✔️ for this PR? It is not emergent but it is getting stale

**Review by tylerlevine — APPROVED** [review]

**Pull request merged**
