### PR TITLE
Bg 62806 eip712 encoding

### PR DESCRIPTION
**Pull request by jeanlarrieux**
[EIP-712 standard](https://eips.ethereum.org/EIPS/eip-712) describe how to encode the data before hashing. This is usually handled by the `@metamask/eth-sig-util` library. Normally we would just call the `eip712hash` function of that library, however that function applies the `keccak` transformation to the encoded data. In our case, we just needed the raw encoding, so we ended up doing everything shy of the `keccak`

### CODE REVIEW

**Review by bitgoAaron — DISMISSED** [review]
sdk-core changes LGTM, but do not merge until ETH team approves.

**Review by olibeyene — APPROVED** [review]
can you update description of the pr?

**Comment by rlutzbitgo** [comment]
Do we care about the socket-security dependency complaint?

**Comment by jeanlarrieux** [comment]
> Do we care about the socket-security dependency complaint?
@bitgoAaron and I spoke about it.

**Review by bitgoAaron — APPROVED** [review]

**Pull request merged**
