### PR TITLE
feat(core): fIx version ripple-keypairs

### PR DESCRIPTION
**Pull request by Joelsx**
FIx version ripple-keypairs

STLX-9667

### CODE REVIEW

**Review by tylerlevine — CHANGES_REQUESTED** [review]
This makes no difference.  Please review the semver behavior using this tool: https://semver.npmjs.com/

**Comment by Joelsx** [comment]
> This makes no difference. Please review the semver behavior using this tool: https://semver.npmjs.com/

We need to set fix the version since rigth now we are having problems with newer versions were they need new npm and node. @FabianSimtlix

**Comment by FabianSimtlix** [comment]
> This makes no difference. Please review the semver behavior using this tool: https://semver.npmjs.com/

Basically with the last version (1.1.0) of this lib this change was added and that's why we need to prevent npm from getting the latest version and continue using the previous one.
image
https://github.com/XRPLF/xrpl.js/blob/ripple-keypairs%401.1.0/packages/ripple-keypairs/package.json

**Comment by tylerlevine** [comment]
> > This makes no difference. Please review the semver behavior using this tool: https://semver.npmjs.com/
> 
> We need to set fix the version since rigth now we are having problems with newer versions were they need new npm and node. @FabianSimtlix

Yes, I understand that. This change will not fix that issue.

> > This makes no difference. Please review the semver behavior using this tool: https://semver.npmjs.com/
> 
> Basically with the last version (1.1.0) of this lib this change was added and that's why we need to prevent npm from getting the latest version and continue using the previous one. image https://github.com/XRPLF/xrpl.js/blob/ripple-keypairs%401.1.0/packages/ripple-keypairs/package.json

Yes, I understand this too. The current semver string precludes version 1.1.0, so it's probably coming in from some transitive dependency.

**Pull request closed without merging**
