### PR TITLE
chore(sdk-coin-ton): add missing tslib dep

### PR DESCRIPTION
**Pull request by Logicwax**
Ticket: HSM-213

### CODE REVIEW

**Review by islamaminBitGo — APPROVED** [review]

**Review by rushilbg — APPROVED** [review]

**Review by gianchandania — COMMENTED** [review]
Github action step seems to be failing as this package is not used in the code, the failing check doesn't seem optional

**Comment by Logicwax** [comment]
> Github action step seems to be failing as this package is not used in the code, the failing check doesn't seem optional

I'm not sure why it thinks that.      We found an issue with hsm-api repo, where pulling in `@bitgo-beta#sdk-coin-ton` caused us to have missing tslib module errors.   A run of `yarn why tslib` even states "Hoisted from "@bitgo-beta#sdk-coin-ton#tonweb#isomorphic-webcrypto"

**Comment by OttoAllmendinger** [comment]
moving to draft until CI is fixed

**Review by OttoAllmendinger — COMMENTED** [review]
flush

**Comment by Logicwax** [comment]
> moving to draft until CI is fixed

this is currently causing us issues with HSM-api deployment on HSM servers (if NODE_ENV is set to anything other than default / development, there is issues).    if this is just blocked due to CI bugs, can DevOps force merge this?     I'm taking this out of draft due to the urgency of this.

**Review by mkottaichamy — APPROVED** [review]

**Comment by Logicwax** [comment]
closing this PR, as https://github.com/BitGo/hsm-api/pull/466 fixes our issue.

**Pull request closed without merging**
