### PR TITLE
fix(sdk-coin-stx): handle baseAddress and memoId in recipient address

### PR DESCRIPTION
**Pull request by bhavidhingra**
TICKET: WIN-2640

## Description

Currently `isValidAddress()` is used to validate the recipient addresses in the `send()` function.
`isValidAddress()` function is meant for validating only the base address. Any valid address having memoId will be considered invalid by this method.
E.g.
isValidAddress('ST1WVJMS5VS41F0YMH7D2M0VHXRG4CY43ZJZBS60A') ==> true
**isValidAddress('ST1WVJMS5VS41F0YMH7D2M0VHXRG4CY43ZJZBS60A?memoId=4') ==> false**

Replacing it will `isValidAddressWithPaymentId()` function because it validates both types of address, having memoId or not.
E.g.
isValidAddressWithPaymentId('ST1WVJMS5VS41F0YMH7D2M0VHXRG4CY43ZJZBS60A') ==> true
**isValidAddressWithPaymentId('ST1WVJMS5VS41F0YMH7D2M0VHXRG4CY43ZJZBS60A?memoId=4') ==> true**

### CODE REVIEW

**Comment by dpkjnr** [comment]
@bhavidhingra please add description how this change will fix the issue mentioned in the ticket, or maybe add comment on the ticket

**Review by mullapudipruthvik — COMMENTED** [review]
please add a test for the same

**Comment by bhavidhingra** [comment]
@dpkjnr Added the description

**Review by dpkjnr — APPROVED** [review]

**Review by mullapudipruthvik — APPROVED** [review]
please click on re-request review button when the PR is ready to review

**Comment by bhavidhingra** [comment]
Moved the fix to wallet-platform https://github.com/BitGo/bitgo-microservices/pull/40064

**Pull request closed without merging**
