### PR TITLE
feat: support ecash transactions

### PR DESCRIPTION
**Pull request by BytesOfMan**
## Description

Adding ecash support to transaction building functions in @bitgo/utxo-lib.

I'm a staff developer for Bitcoin ABC working to organize a dev stack for eCash. The Bitgo library is already well tested and supported. However, it requires some shims and user workarounds in order to support eCash transaction building. Ideally this would be abstracted into the library as it is for other cryptocurrencies here such as Bitcoin Cash.

I have managed to get the BitcoinABC web wallet, [Cashtab](https://cashtab.com/), [working with @bitgo/utxo-lib 7.3.0.](https://reviews.bitcoinabc.org/D12948) I would like to remove the version number shim necessary to get this functionality without direct support in the library.

## Issue Number

N/A

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

I installed this local version of `@bitgo/utxo-lib` into this diff. Cashtab is able to create and broadcast valid eCash txs. Cashtab unit tests (which include creating txs that match expected rawtx hex) pass when version shim (`txBuilder.__TX.version = 2;` before calling `txBuilder.sign`) is removed.

The changes to `UtxoPsbt` and the changes in `signature.ts` have not been tested. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code compiles correctly for both Node and Browser environments
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My commits follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) and I have properly described any BREAKING CHANGES
- [x] The ticket or github issue was included in the commit message as a reference
- [x] I have made corresponding changes to the documentation and on any new/updated functions and/or methods - [jsdoc](https://jsdoc.app/) 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by brandonblack** [comment]
Thanks for your contribution! I took a glance at the linked PR, and we can't recommend new code that uses `TransactionBuilder` as its been removed upstream, and the version contained here is considered deprecated. Inside BitGo, we're moving all of our systems to use PSBT instead.

That is somewhat separate from this PR itself though. For this PR, can you please create an issue to reference to make our linter happy?

**Comment by brandonblack** [comment]
Thanks for adding that issue! Apparently we need better docs:

In the body of your commit message add a line like `Issues: Bitgo#3161` instead of in the subject to satisfy the linter.

**Review by OttoAllmendinger — CHANGES_REQUESTED** [review]
please enable the following test suite for ecash and add the fixtures  https://github.com/BitGo/BitGoJS/blob/294c729c483a734e620f8b5f162d09845d382d41/modules/utxo-lib/test/integration_local_rpc/parse.ts#L298

you will have to provide values here 

https://github.com/BitGo/BitGoJS/blob/442e7e9df3acd00edde3a0512de363164a377bb5/modules/utxo-lib/test/integration_local_rpc/generate/regtestNode.ts#L28

and generate the fixtures with this script https://github.com/BitGo/BitGoJS/blob/3186934f8af3a3d50d3b8890446008e7bee06d90/modules/utxo-lib/test/integration_local_rpc/generate/main.ts#L195

**Comment by BytesOfMan** [comment]
> and generate the fixtures with this script

I think I'm just missing something here or going about it the wrong way. How is the script run?

When I try `node main.ts` (`v16.14.2`), I get the following:

```
import * as assert from 'assert';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Thanks!

**Comment by BytesOfMan** [comment]
For reference, Docker notes for ecash node client at https://hub.docker.com/r/bitcoinabc/bitcoin-abc/

**Comment by BytesOfMan** [comment]
> Thanks for your contribution! I took a glance at the linked PR, and we can't recommend new code that uses `TransactionBuilder` as its been removed upstream, and the version contained here is considered deprecated. Inside BitGo, we're moving all of our systems to use PSBT instead.

I'm still only seeing `TransactionBuilder` in the `Usage` section of the README. For my app, I'd like to move to PSBT -- would also like to move to Schnorr signing for transaction building (also supported in BCH). 

Is PSBT ready to roll in this library? Are there syntax examples available? If not, I can create an issue and add some of this to the `utxo-lib` README.md.

Thanks!

**Comment by davidkaplanbitgo** [comment]
> Is PSBT ready to roll in this library? 

PSBTs (referring to [`UtxoPsbt`](https://github.com/BitGo/BitGoJS/blob/master/modules/utxo-lib/src/bitgo/UtxoPsbt.ts#L45)) are *mostly* ready to roll in this library - all of the work is done, but we are still working on overriding some of the base PSBT methods such as `UtxoPsbt.clone` (this should be fixed by the end of the week). The `clone` method is the only one we are aware of that is not working properly, all others have been addresses ASAIK.

> Are there syntax examples available? If not, I can create an issue and add some of this to the `utxo-lib` README.md.

We haven't updated the majority of the documentation yet, this is currently a work in progress, and is something that I can probably expedite doing. Is there anything in particular you are interested in seeing examples of?

**Comment by BytesOfMan** [comment]
> Is there anything in particular you are interested in seeing examples of?

The more the better but, for immediate selfish purposes, just basic transactions would be great. Cashtab creates conventional p2pkh transactions. Would also be great if schnorr signing for these txs were available.

So, an app that uses this library to make this kind of transaction for Bitcoin Cash would have pretty much the same syntax.

**Comment by OttoAllmendinger** [comment]
> 
> I think I'm just missing something here or going about it the wrong way. How is the script run?

Try `yarn ts-node path/to/script.ts`

**Comment by brandonblack** [comment]
> Would also be great if schnorr signing for these txs were available.

BCH has schnorr signing for P2PKH inputs? As of now, this library only supports Schnorr signing for P2TR outputs (as that's what's supported in BTC).

**Comment by BytesOfMan** [comment]
> > Would also be great if schnorr signing for these txs were available.
> 
> ecash has schnorr signing for P2PKH inputs? As of now, this library only supports Schnorr signing for P2TR outputs (as that's what's supported in BTC).

Yes, BCH too. You can make these transactions using [ElectronCash](https://electroncash.org/) (BCH) or [ElectrumABC](https://www.bitcoinabc.org/electrum/) (eCash). Don't currently have a good JS library for doing them in a react app like Cashtab. 

The spec is slightly different for eCash/BCH vs BTC.

[BCH/eCash schnorr spec](https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/2019-05-15-schnorr.md)

[BTC spec](https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki)

**Comment by BytesOfMan** [comment]
> Try `yarn ts-node path/to/script.ts`

Most recent changes were made by...

1. Running local ecash node with `testnet=1` , version 0.26.9 (most recent)
2. `RPC_ECASHTEST='http://<rpcuser>:<rpcpassword>@localhost:18332' yarn ts-node test/integration_local_rpc/generate/main.ts ecash`

I also used the param `ecash=0`. `ecash=1` is default for new versions.

Running the testnet node without `ecash=0` threw this error from attempting to run `main.ts ecash`:

```
rpcError: { code: -6, message: 'Transaction amount too small' }
```

Probably related to `ecash=1` using units of bits instead of satoshis.

**Comment by BytesOfMan** [comment]
Re: `7e0ef79` commit

I attempted to run script again with `ecash=1`, which deleted the generated files when the above described "Transaction amount too small" error was thrown.

Re-ran with `ecash=0` and pushed up results in new commit.

**Comment by brandonblack** [comment]
Since you deleted all fixtures files, but then only ran the generate for ecash, a bunch of unrelated fixtures were removed. Can you undelete those?

> Schnorr

We used to have our own implementation of Schnorr BIP340 signing, which would have been fairly easy to adapt to support ecash/BCH Schnorr signatures, but now moved to use upstream implementations of Schnorr signing. If you want to get ecash/BCH Schnorr signature support into this library, I think the path would have to be to get it added to `noble-secp256k1` first, and then make a PR here to support it. Caveat emptor the changes to support the actual signature algorithm will be relatively small, but threading support through `Transaction`, and `PSBT` will be a pretty large undertaking.

**Comment by BytesOfMan** [comment]
> Since you deleted all fixtures files, but then only ran the generate for ecash, a bunch of unrelated fixtures were removed. Can you undelete those?

Yes, will get these back in. 

FYI I did not go through and delete the files -- they were deleted when I ran the script with `RPC_ECASHTEST='http://<rpcuser>:<rpcpassword>@localhost:18332' yarn ts-node test/integration_local_rpc/generate/main.ts ecash`. Since I ran it several times while troubleshooting my own node settings, I'm not sure if this was a consequence to one of the runs that threw an error message.

> If you want to get ecash/BCH Schnorr signature support into this library ...

Will dig into this, thanks for pointing out the right path here.

**Comment by BytesOfMan** [comment]
Update:

- Rebased to latest master
- Moved back the files from `v1/testnet`
- Re-ran `RPC_ECASHTEST='http://<rpcuser>:<rpcpassword>@localhost:18332' yarn ts-node test/integration_local_rpc/generate/main.ts ecash`. This time, only the relevant eCash files were updated. So, I must have deleted the other files earlier by running the script in an error condition, or making some other error when trying to run the script.

**Review by OttoAllmendinger — DISMISSED** [review]

**Comment by OttoAllmendinger** [comment]
@BytesOfMan to satisfy the commit linter you can add `Issue: BG-0` at the end of your coomit

**Comment by BytesOfMan** [comment]
> > Is PSBT ready to roll in this library?
> 
> PSBTs (referring to [`UtxoPsbt`](https://github.com/BitGo/BitGoJS/blob/master/modules/utxo-lib/src/bitgo/UtxoPsbt.ts#L45)) are _mostly_ ready to roll in this library - all of the work is done, but we are still working on overriding some of the base PSBT methods such as `UtxoPsbt.clone` (this should be fixed by the end of the week). The `clone` method is the only one we are aware of that is not working properly, all others have been addressed ASAIK. You should be able to use PSBTs in your app.
> 
> > Are there syntax examples available? If not, I can create an issue and add some of this to the `utxo-lib` README.md.
> 
> We haven't updated the majority of the documentation yet, this is currently a work in progress, and is something that I can probably expedite doing. Is there anything in particular you are interested in seeing examples of?

Are there any examples for using PSBT to create non-segwit transactions other than [this one?](https://github.com/bitcoinjs/bitcoinjs-lib/blob/9ae208926d02b8e81842bb1942db39279ed2491c/test/integration/transactions.spec.ts#L36)

Looks like to get this to work in Cashtab, I would need to look up the previous rawtx by txid (or change the indexer such that looking up utxos at an address returns objects that include hex rawtxs).

Am I interpreting that correctly? How does Bitgo use PSBT for creating BCH txs?

:pray:

**Comment by davidkaplanbitgo** [comment]
> Are there any examples for using PSBT to create non-segwit transactions other than [this one?](https://github.com/bitcoinjs/bitcoinjs-lib/blob/9ae208926d02b8e81842bb1942db39279ed2491c/test/integration/transactions.spec.ts#L36)

>  How does Bitgo use PSBT for creating BCH txs?

There are in the tests of `BitgoJS`, however most of them are about parsing from a transaction. Here is approximately how you would instantiate it for the BCH network:

```typescript

const psbt = utxolib.bitgo.createPsbtForNetwork({ network: utxolib.networks.bitcoincash });

// Add/update your inputs and outputs
psbt.addInput({ ... });
psbt.addOutput({ ... });

// If you want to get the unsigned transaction from here:
const unsignedTx = psbt.getUnsignedTx();

// Sign the inputs
psbt.signAllInputs(...);

// Finalize and extract
psbt.finalizeAllInputs();
const fullySignedTx = psbt.extractTx();

```

> Looks like to get this to work in Cashtab, I would need to look up the previous rawtx by txid (or change the indexer such that looking up utxos at an address returns objects that include hex rawtxs). Am I interpreting that correctly?

In general for non-segwit unspents you need the previous transaction buffer as the `nonWitnessUtxo` of the unspent because the psbt needs to be able to verify the value of the transaction. It is not able to do this directly because for non-segwit transactions the value is not hashed. To get around this, you need to add the previous transaction hash so that the psbt can verify the value *indirectly* by checking the value of the previous transaction. The only exception that I am aware of  this is Zcash, where their non-segwit transactions do hash the value, so it would be unnecessary for them.

**Comment by BytesOfMan** [comment]
rebased to latest master and added "Issue: BG-0" to all commit msgs to resolve linter issue

**Comment by BytesOfMan** [comment]
`getRawTransactionVerbose` returns txs with the `addresses` field of `vout` in cashaddress format

https://github.com/BitGo/BitGoJS/blob/master/modules/utxo-lib/test/integration_local_rpc/generate/RpcClient.ts#L128

but the unit test comparison returns addresses in base58. 

The BCH fixtures have addresses in legacy format, e.g. here: https://github.com/BitGo/BitGoJS/blob/master/modules/utxo-lib/test/integration_local_rpc/fixtures/bitcoincashTestnet/v2/deposit_p2sh.json#L29

Were they manually set that way? BitcoinCash nodes also return addresses in cashaddress format from `getrawtransaction` calls with `verbose=true`, e.g. 

```
curl -X GET "https://api.fullstack.cash/v5/rawtransactions/getRawTransaction/fe28050b93faea61fa88c4c630f0e1f0a1c24d0082dd0e10d369e13212128f33?verbose=true" -H "accept: application/json"
```

Let me know if it's ok to manually adjust the address format in the eCash fixtures (i.e. by using something like https://converter.bitcoinabc.org/). The alt approach would be to get cashaddress support in the comparison result...I think here:

https://github.com/BitGo/BitGoJS/blob/master/modules/utxo-lib/test/integration_local_rpc/parse.ts#L75

:pray:

**Comment by BytesOfMan** [comment]
Corrected ecash rpc settings so addresses are in legacy, matching `bitcoincash` implementation

**Comment by BytesOfMan** [comment]
rebase to latest master

**Comment by BytesOfMan** [comment]
- Found and patched issue causing unit test tx mismatch (see change to `compare.ts`)
- Regenerated ecash fixtures to get values that do not fail `Number.isSafeInteger`

**Comment by BytesOfMan** [comment]
rebase to latest master

**Comment by BytesOfMan** [comment]
Looks like these unit test failures are related to Cardano and an env variable and not this diff. 

Does this failure block merging?

```
@bitgo/sdk-coin-ada:   1) ADA
@bitgo/sdk-coin-ada:        "before all" hook for "should instantiate the coin":
@bitgo/sdk-coin-ada:      Error: Need to set BITGOJS_TEST_PASSWORD env variable - please see the developer setup docs.
@bitgo/sdk-coin-ada:       at Function.decorate (/home/runner/work/BitGoJS/BitGoJS/modules/sdk-test/src/bitgo/lib/test_bitgo.ts:140:13)
@bitgo/sdk-coin-ada:       at Context.<anonymous> (test/unit/ada.ts:74:23)
@bitgo/sdk-coin-ada:       at processImmediate (node:internal/timers:466:21)
@bitgo/sdk-coin-ada:   2) Ada
@bitgo/sdk-coin-ada:        "before all" hook for "should instantiate the coin":
@bitgo/sdk-coin-ada:      Error: Need to set BITGOJS_TEST_PASSWORD env variable - please see the developer setup docs.
@bitgo/sdk-coin-ada:       at Function.decorate (/home/runner/work/BitGoJS/BitGoJS/modules/sdk-test/src/bitgo/lib/test_bitgo.ts:140:13)
@bitgo/sdk-coin-ada:       at Context.<anonymous> (test/unit/index.ts:11:23)
@bitgo/sdk-coin-ada:       at processImmediate (node:internal/timers:466:21)
@bitgo/sdk-coin-ada: error Command failed with exit code 2.
```

**Comment by BytesOfMan** [comment]
rebase to latest master

**Comment by BytesOfMan** [comment]
rebase to latest master

**Comment by BytesOfMan** [comment]
rebase to latest master

**Comment by BytesOfMan** [comment]
rebase to latest master

**Comment by BytesOfMan** [comment]
rebase to latest master.

**Comment by BytesOfMan** [comment]
rebase to latest master

**Comment by BytesOfMan** [comment]
Ok -- unit tests are passing except for the required Bitgo password.

From [DEVELOPERS.md](https://github.com/BitGo/BitGoJS/blob/master/DEVELOPERS.md) at the top level of this repo:

```
Once your code is passing unit tests and has an initial review, a BitGo engineer will re-create your PR and sign your commits, and link back to the original PR.
```

Let me know if there's anything else I can do to support this step :pray:

**Comment by byhow** [comment]
@BytesOfMan I cherry-picked the commits here into #3160. Let's move the conversation over there. Thanks!

**Comment by OttoAllmendinger** [comment]
@BytesOfMan I believe we can close this PR then?

**Review by OttoAllmendinger — COMMENTED** [review]
flush queue, see prev comment

**Comment by BytesOfMan** [comment]
> @BytesOfMan I believe we can close this PR then?

Yes, since this one can't land and is superseded by #3294

**Pull request closed without merging**
