### PR TITLE
chore: add step to drone to check managed package version numbers 

### PR DESCRIPTION
**Pull request by tylerlevine**
Check versions of in-repo packages to make sure they match with the package.json version.
This is to prevent inadvertent updates of dependency versions for packages which are symlinked
by lerna. The dependency versions of these packages should only ever be updated in the release branch.

Ticket: BG-31227

### CODE REVIEW

**Review by ericcrosson-bitgo — DISMISSED** [review]
automation station :bullettrain_side:

**Comment by tylerlevine** [comment]
Going to replace this with a node script so I don't have to install jq in the build container.

**Comment by ericcrosson-bitgo** [comment]
> Going to replace this with a node script so I don't have to install jq in the build container.

Are you interested in using [@typescript-tools/pin-lerna-package-versions](https://github.com/typescript-tools/typescript-tools/tree/master/packages/pin-lerna-package-versions) or contributing something like a `--check` flag? 

The function `pin-lerna-package-versions` uses to find dependencies, `@typescript-tools/lerna-packages`, is [open-source](https://www.npmjs.com/package/@typescript-tools/lerna-packages). Documentation is shoddy but [types are strong](https://github.com/typescript-tools/typescript-tools/blob/7939e6eb8ed5b05f49529f9e16cd5242f80c5d58/packages/lerna-packages/src/index.ts#L41) and [here](https://github.com/typescript-tools/typescript-tools/blob/7939e6eb8ed5b05f49529f9e16cd5242f80c5d58/packages/pin-lerna-package-versions/src/index.ts#L184) is an example of use.

**Comment by tylerlevine** [comment]
Seems to be doing the right thing: https://cloud.drone.io/BitGo/BitGoJS/7524/1/5

**Comment by tylerlevine** [comment]
Need to wait for the next stable release to go out, then I think we can merge this and start enforcing.

**Review by twtaylorbitgo — APPROVED** [review]

**Pull request merged**
