### PR TITLE
feat(key-card): add basic code to generate key cards

### PR DESCRIPTION
**Pull request by LeoKotschenreuther**
* adds code in the key-card module that creates the key cards
* skips the QR codes on the key-cards for now, will come in a
  followup
* adds some sample code in the web-demo module that allows creation
  of a sample key card

Ticket: BG-64432

## Test Instructions

* check out the PR branch locally
* run the following commands
```
yarn install
cd modules/web-demo
yarn dev
```
Open `localhost:8080/keycard` in your browser and click on the Download button. This should generate and download a key card, compare it against the one attached to this PR:
[BitGo Keycard for Hello World.pdf](https://github.com/BitGo/BitGoJS/files/10675748/BitGo.Keycard.for.Hello.World.pdf)

### CODE REVIEW

**Comment by LeoKotschenreuther** [comment]
I'm all ears on how we can test this code in an automated way. I couldn't come up with an easy solution.

**Review by pengyuc-bitgo — DISMISSED** [review]

**Comment by LeoKotschenreuther** [comment]
Sorry for the noise, I totally forgot that I still have to manually run the code to see whether it works

**Review by sachushaji — COMMENTED** [review]
Flushing dev rel team review queue, Kindly re-request when ready

**Comment by LeoKotschenreuther** [comment]
For now I also skipped including an image on the key card. Let me know if I should add one. Any ideas for an image to use? Is it ok to grab one with a BitGo logo & a coin logo that we currently put on the key cards generated upon wallet creation in the BitGo UI?

**Review by zahin-mohammad — APPROVED** [review]

**Review by rlutzbitgo — APPROVED** [review]
I'm also curious about your image/logo question, but I suppose we can always revisit if given some guidance there

**Review by jicli — APPROVED** [review]

**Review by byhow — APPROVED** [review]

**Review by sachushaji — APPROVED** [review]

**Review by sachushaji — COMMENTED** [review]
I tried out the webdemo, It downloaded keycard successfully, The only missing thing was the QRcode which I think probably you might be planning to add in a follow up right?

**Pull request merged**
