### PR TITLE
fix(account-lib): fix chaincode to use correct modulo

### PR DESCRIPTION
**Pull request by sachushaji**
fix modulus for chaincode to be 2^256

TICKET: BG-50457

### CODE REVIEW

**Review by johnoliverdriscoll — DISMISSED** [review]

**Review by olibeyene — APPROVED** [review]

**Review by tylerlevine — CHANGES_REQUESTED** [review]
test?

**Review by tylerlevine — CHANGES_REQUESTED** [review]
test case passes without the implementation change. Are you sure this actually tests the new behavior?

**Comment by sachushaji** [comment]
@tylerlevine previous modulus was less than the current modulo, so it will pass for the earlier implementation

**Comment by sachushaji** [comment]
@tylerlevine Actually,the previous test case for this was only cheking with a simple NULL. This test case correctly checks the value for chaincode. So it should be okay

**Review by tylerlevine — APPROVED** [review]

**Pull request merged**
