### PR TITLE
test(abstract-eth): move address init tests to abstract-eth

### PR DESCRIPTION
**Pull request by gianchandania**
WIN-1926

This PR moves address init tests to abstract-eth
TICKET: WIN-1926

### CODE REVIEW

**Review by OttoAllmendinger — COMMENTED** [review]
Automatic comment to flush this PR from my review queue. 🚽🚽🚽
Please re-request another review from the respective team(s) when you are ready for reviews.

**Review by lcovar — COMMENTED** [review]
flushing

**Review by mmcshinsky-bitgo — COMMENTED** [review]
`bitgo` module doesn't have a `fix(sdk-core)`. Can we move it out of this commit to not trigger an unneeded version bump?

**Review by zahin-mohammad — COMMENTED** [review]
flush

**Pull request closed without merging**
