### PR TITLE
feat: add ecash tx support

### PR DESCRIPTION
**Pull request by byhow**
Due to workflow concerns [here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) and from Github [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request): 
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

The unit test won't be passing from forks since the secrets are hidden from PRs that come from forks. More reference [here](https://dev.to/petrsvihlik/using-environment-protection-rules-to-secure-secrets-when-building-external-forks-with-pullrequesttarget-hci)

I know this might be a pain but we haven't been getting feedback on alternatives to Github's convention both internally and externally, so in the short run, we will follow the standards that you @BytesOfMan mentioned [here](https://github.com/BitGo/BitGoJS/pull/3160#issuecomment-1430530645) in #3160. I have not changed anything from #3160, and I am merely cherry-picking the commits onto a repo branch from a forked branch.

Again, thanks for your contribution! @BytesOfMan 

Ticket: BG-68290

Closes: #3160

### CODE REVIEW

**Comment by byhow** [comment]
For reviewers, please refer to the discussion in #3160 for context, thanks!

**Comment by BytesOfMan** [comment]
OK -- hadn't seen this test yet.

From the output, looks like [these fixtures](https://github.com/BitGo/BitGoJS/tree/master/modules/bitgo/test/v2/unit/coins/utxo/fixtures/bcha) need to be updated. This makes sense as they are using tx version 1, while the PR is moving to version 2 for ecash default.

Is there a script for generating these fixtures, like there was for the other fixtures (see discussion in #3160)?

:pray:

**Comment by OttoAllmendinger** [comment]
in general, you can recreate fixtures by deleting the fixture files and re-running the tests that use them

**Comment by BytesOfMan** [comment]
OK. I am unable to run these tests locally.

```
$ yarn run unit-test --scope bitgo
yarn run v1.22.19
$ lerna run unit-test --stream --scope bitgo
lerna notice cli v5.6.2
lerna info versioning independent
lerna notice filter including "bitgo"
lerna info filter [ 'bitgo' ]
lerna info Executing command in 1 package: "yarn run unit-test"
bitgo: $ mocha
bitgo: Error: Need to set BITGOJS_TEST_PASSWORD env variable - please see the developer setup docs.
```

@byhow , could you try

```
cd BitGoJS
rm -rf modules/bitgo/test/v2/unit/coins/utxo/fixtures/bcha
yarn run unit-test --scope bitgo
```

or, if there is some way I could get some kind of temp password that lets me run these on the ecash scope, can email me at joey@e.cash

Thanks!

**Comment by byhow** [comment]
>  could you try
cd BitGoJS
rm -rf modules/bitgo/test/v2/unit/coins/utxo/fixtures/bcha
yarn run unit-test --scope bitgo

@BytesOfMan Done! Tests should be passing

**Review by OttoAllmendinger — APPROVED** [review]

**Review by mmcshinsky-bitgo — APPROVED** [review]

**Pull request merged**
