### PR TITLE
feat(account-lib): Add AvaxWalletSimple.sol ABI to walletUtil.ts

### PR DESCRIPTION
**Pull request by nachofm**
Add AvaxWalletSimple.sol ABI to walletUtil.ts

JIRA Ticket: https://bitgoinc.atlassian.net/browse/STLX-5726

Changes:
Add AvaxWalletSimple.sol ABI to walletUtil.ts

### CODE REVIEW

**Review by smaria95 — DISMISSED** [review]
LGTM

**Review by jrafael-simtlix — APPROVED** [review]

**Review by CapnMigraine — DISMISSED** [review]
lgtm, although I can't find where this is used. 
cc: @BitGo/eth-team

**Review by twtaylorbitgo — CHANGES_REQUESTED** [review]
Please post how the ABI was generated here, we'll need the step by step and compiler version. This is also not acceptable as I don't see this contract committed anywhere.

**Comment by CapnMigraine** [comment]
> Please post how the ABI was generated here, we'll need the step by step and compiler version. This is also not acceptable as I don't see this contract committed anywhere.

Thanks for reviewing @twtaylorbitgo. We already committed the contract to [eth-multisig-v2](https://github.com/BitGo/eth-multisig-v2/pull/27)
I just want to know if `walletSimpleAbi` is used anywhere, I don't see any references to it.

**Comment by nachofm** [comment]
> Please post how the ABI was generated here, we'll need the step by step and compiler version. This is also not acceptable as I don't see this contract committed anywhere.

The steps used to obtain the ABI of the contract were:
1.  Go to: https://remix.ethereum.org/
2.  Copy the content of the contract [AvaxWalletSimple.sol](https://github.com/BitGo/eth-multisig-v2/pull/27/files) into the IDE
3.  The content of the contracts: [Forwarder.sol](https://github.com/BitGo/eth-multisig-v2/blob/master/contracts/Forwarder.sol) and [ERC20Interface.sol](https://github.com/BitGo/eth-multisig-v2/blob/master/contracts/ERC20Interface.sol) also need to be present to replicate the imports structure of AvaxWalletSimple.sol
4.  Compile the contract with the compiler version 0.4.26+commit.4563c3fc and then get the generated ABI

**Comment by nachofm** [comment]
> > Please post how the ABI was generated here, we'll need the step by step and compiler version. This is also not acceptable as I don't see this contract committed anywhere.
> 
> @twtaylorbitgo @CapnMigraine :
> 
> The steps used to obtain the ABI of the contract were:
> 
>     1. Go to: https://remix.ethereum.org/
> 
>     2. Copy the content of the contract [AvaxWalletSimple.sol](https://github.com/BitGo/eth-multisig-v2/pull/27/files) into the IDE
> 
>     3. The content of the contracts: [Forwarder.sol](https://github.com/BitGo/eth-multisig-v2/blob/master/contracts/Forwarder.sol) and [ERC20Interface.sol](https://github.com/BitGo/eth-multisig-v2/blob/master/contracts/ERC20Interface.sol) also need to be present to replicate the imports structure of AvaxWalletSimple.sol
> 
>     4. Compile the contract with the compiler version 0.4.26+commit.4563c3fc and then get the generated ABI

Added the comment as part of the code, above the walletSimpleAbi constant as discussed with @CapnMigraine and @twtaylorbitgo

**Review by CapnMigraine — APPROVED** [review]

**Review by twtaylorbitgo — APPROVED** [review]

**Pull request merged**
