### PR TITLE
feat(sdk-coin-avaxc): add avaxc support for evm ccr

### PR DESCRIPTION
**Pull request by nrjsuthar**
TICKET: COIN-1708

### CODE REVIEW

**Review by Vijay-Jagannathan — COMMENTED** [review]
failing some build

**Comment by venkateshv1266** [comment]
Since there is a dependency addition in package.json, we might need to add package-lock.json file as well.

**Comment by venkateshv1266** [comment]
Still some change is needed in the PR to by-pass fetching gasprice and gaslimit function call only for AVAXC in the file `abstractEthLikeNewCoins.ts`. 
Here for gasPrice https://github.com/BitGo/BitGoJS/blob/COIN-1708/modules/abstract-eth/src/abstractEthLikeNewCoins.ts#L1529
Here for gasLimit (native): https://github.com/BitGo/BitGoJS/blob/COIN-1708/modules/abstract-eth/src/abstractEthLikeNewCoins.ts#L1639 
Here for gasLimit (token): https://github.com/BitGo/BitGoJS/blob/COIN-1708/modules/abstract-eth/src/abstractEthLikeNewCoins.ts#L1808

If not, we are unable to generate half-signed transaction from WRW.

**Review by OttoAllmendinger — APPROVED** [review]

**Review by zahin-mohammad — CHANGES_REQUESTED** [review]
Why is there bera token commits for a pr for avaxc?

**Pull request closed without merging**
