### PR TITLE
fix(statics)!: Fix mismatched erc20 token config

### PR DESCRIPTION
**Pull request by dpkjnr**
Ticket: BG-52965

[BG-52965]: https://bitgoinc.atlassian.net/browse/BG-52965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by dpkjnr** [comment]
please check conversation https://bitgo.slack.com/archives/C01TVUJGU2K/p1671002601214839 for more details

**Review by mmcshinsky-bitgo — CHANGES_REQUESTED** [review]
Breaking Change missing from commit footer.

**Comment by dpkjnr** [comment]
> Breaking Change missing from commit footer.

@mmcshinsky-bitgo I didn't understand what I need to change

**Comment by sachushaji** [comment]
> > Breaking Change missing from commit footer.
> 
> @mmcshinsky-bitgo I didn't understand what I need to change

since you are changing a previously published symbol and also changing the underlying asset, its a breaking change. Check [here](https://www.conventionalcommits.org/en/v1.0.0/#:~:text=in%20Semantic%20Versioning\).-,BREAKING,-CHANGE%3A%20a) for commit standard for reference

**Comment by mmcshinsky-bitgo** [comment]
Breaking change comment needs to move to the commit footer and you'll be good to go.

**Comment by dpkjnr** [comment]
> Breaking change comment needs to move to the commit footer and you'll be good to go.

done

**Review by mmcshinsky-bitgo — APPROVED** [review]

**Pull request merged**
